// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from '@env/.env';
import { KEYCLOAK } from '@app/constants';

export const environment = {
  production: false,
  version:
    'CORE: ' +
    env['npm_package_version'] +
    ', tieto-dev-config-server: 2022.3.1 A14',
  serverUrl: '/api/v3',
  configServerUrl: '/config-server',
  configServerRequests: ['/tenant'],
  defaultLanguage: 'fi-FI',
  languageParameter: false,
  supportedLanguages: ['fi-FI', 'sv-SE', 'en-US'],
  translationLanguages: ['fi-FI', 'sv-SE', 'en-US'],
  defaultCountry: 'FI',
  authenticationUrl:
    'https://authserver.dev.scheduler.cemcloud.io/authenticate',
  refreshUrl: 'https://authserver.dev.scheduler.cemcloud.io/refresh',
  unauthenticationUrl: '',
  tenantRefreshUrl: '',
  assets: 'assets/',
  brand: 'assets/brand/',
  sitekey: '',
  defaultView: 'tenant',
  authMode: KEYCLOAK,
  timezone: false,
  termsAndConditionsAccepted: true,
  storagePrefix: 'config-server.',
  gaTrackID: false,
  gtm: false,
  showUserData: true,
  defaultImage: 'default_image.png',
  logoFi: 'main-logo.svg',
  logoSv: 'main-logo.svg',
  logoEn: 'main-logo.svg',
  customerInfoParameter: false,
  editMeetingParameter: false,
  returnUrlParameter: false,
  extraUrlParameter: false,
  tenantParameter: false,
  customerCareParameter: false,
  storageParameter: false,
  timeStamp: '',
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
