// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from '@env/.env';
import { SCHEDULER, KEYCLOAK } from '@app/constants';

export const environment = {
  production: true,
  version:
    'CORE: ' + env['npm_package_version'] + ', tieto-prod-agent: 2022.3.1 A14',
  serverUrl: 'https://api.dev.scheduler.cemcloud.io/api/v3',
  configServerUrl: false,
  configServerRequests: false,
  defaultLanguage: 'fi-FI',
  languageParameter: false,
  supportedLanguages: ['fi-FI', 'sv-SE', 'en-US'],
  translationLanguages: ['fi-FI', 'sv-SE', 'en-US'],
  defaultCountry: 'FI',
  authenticationUrl:
    'https://authserver.dev.scheduler.cemcloud.io/authenticate',
  refreshUrl: 'https://authserver.dev.scheduler.cemcloud.io/refresh',
  unauthenticationUrl: '',
  tenantRefreshUrl: '',
  assets: 'assets/',
  brand: 'assets/brand/',
  sitekey: '',
  defaultView: SCHEDULER,
  authMode: KEYCLOAK,
  timezone: false,
  termsAndConditionsAccepted: true,
  storagePrefix: 'scheduler.',
  gaTrackID: false,
  gtm: false,
  showUserData: false,
  defaultImage: 'default_image.png',
  logoFi: 'main-logo.svg',
  logoSv: 'main-logo.svg',
  logoEn: 'main-logo.svg',
  customerInfoParameter: 'boaId',
  editMeetingParameter: false,
  returnUrlParameter: false,
  extraUrlParameter: false,
  tenantParameter: false,
  customerCareParameter: false,
  storageParameter: false,
  timeStamp: '',
};
